name: Build and Deploy to OpenShift

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CLI tools from OpenShift Mirror
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: latest
    
      # 2. Log in to OpenShift
      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
    
      - name: Build Docker image with Buildah
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: hello-world-app
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Dockerfile


      - name: Push image to quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/quay-user
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Deploy application in OpenShift
        uses: redhat-actions/oc-new-app@v1
        with:
          app_name: hello-world-app
          image: quay.io/${{ secrets.QUAY_USER }}/hello-world-app:latest
          namespace: my-openshift-namespace
          
      - name: expose service
        run: |
          oc expose svc/hello-world-app
