name: Build and Deploy to OpenShift

env:
  IMAGE_NAME: "startup-live-events"
  NAMESPACE: "github-test-1"

on:
  workflow_dispatch:
    inputs:
      branches:
        type: choice
        description: 'Branch to deploy'
        default: 'main'
        options:
          - 'main'
          - 'develop'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CLI tools from OpenShift Mirror
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: latest
    
      - name: Log in to OpenShift
        run: |
          oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER }}
          oc project ${{ env.NAMESPACE }}
      
      - name: Build Docker image
        run: podman build -t ${{ env.IMAGE_NAME }} .

      - name: Push Docker image to OpenShift registry
        run: |
          podman login -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_PASSWORD }}) quay.io
          podman push quay.io/${{ secrets.QUAY_USER }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy application in OpenShift
        run: |
          oc project github-test-1
          oc new-app ${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest --name=${{ env.IMAGE_NAME }} || true
          oc expose svc/${{ env.IMAGE_NAME }} || true
