name: Build and Deploy to OpenShift

on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: "hello-world-app"
  TAG: "latest"
  NAMESPACE: "github-test-1"
  REGISTRY_BASE: "quay.io/${{ secrets.QUAY_USER }}"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CLI tools from OpenShift Mirror
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: latest
    
      # 2. Log in to OpenShift
      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ env.NAMESPACE }}
    
      - name: Build Docker image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAG }}
          containerfiles: |
            ./Dockerfile


      - name: Push image to quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAG }}
          registry: ${{ env.REGISTRY_BASE }}
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Deploy application in OpenShift
        uses: redhat-actions/oc-new-app@v1
        with:
          app_name: ${{ env.IMAGE_NAME }}
          image: ${{ env.REGISTRY_BASE }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          namespace: ${{ env.NAMESPACE }}

