name: Build and Deploy to OpenShift

on:
  workflow_dispatch:
    inputs:
      branches:
        type: choice
        description: 'Branch to deploy'
        default: 'main'
        options:
          - 'main'
          - 'develop'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CLI tools from OpenShift Mirror
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: latest
    
      # 2. Log in to OpenShift
      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

      # 3. Build the Docker image
      - name: Build Docker image
        run: podman build -t hello-world-app .

      # 5. Push the image to the OpenShift internal registry
      - name: Push Docker image to OpenShift registry
        run: |
          podman login -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_PASSWORD }}) quay.io
          podman push quay.io/${{ secrets.QUAY_USER }}/hello-world-app:latest

      # 6. Deploy the application in OpenShift
      - name: Deploy application in OpenShift
        run: |
          oc project github-test-1
          oc new-app my-project/hello-world-app:latest --name=hello-world-app || true
          oc expose svc/hello-world-app || true
